name: Test - Parallelization

on:
  workflow_dispatch:
  push:
    branches:
      - "demo/**"

env:
  DD_ENV: ci
  DD_SERVICE: demo-parallel
  PYTEST_ADDOPTS: "--ignore=tests/flaky"
  DD_TEST_OPTIMIZATION_RUNNER_PLATFORM: python
  DD_TEST_OPTIMIZATION_RUNNER_FRAMEWORK: pytest
  DD_TEST_OPTIMIZATION_RUNNER_MIN_PARALLELISM: 1
  DD_TEST_OPTIMIZATION_RUNNER_MAX_PARALLELISM: 8

jobs:
  dd_plan:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.dd_plan.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-demo
        with:
          install_ddtest: "true"
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
      - id: dd_plan
        name: Plan test execution
        run: bin/ddtest plan
        env:
          DD_ENV: ci
          DD_SERVICE: demo-parallel
          DD_CIVISIBILITY_ITR_ENABLED: "false"
      - uses: actions/upload-artifact@v4
        with:
          name: dd-artifacts-parallel
          path: .testoptimization
          include-hidden-files: true

  dd_test:
    runs-on: ubuntu-latest
    needs: [dd_plan]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.dd_plan.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-demo
        with:
          install_ddtest: "true"
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
      - uses: actions/download-artifact@v4
        with:
          name: dd-artifacts-parallel
          path: .testoptimization
      - name: Run parallel tests
        run: bin/ddtest run --ci-node ${{ matrix.ci_node_index }}
        env:
          DD_ENV: ci
          DD_SERVICE: demo-parallel
          DD_CIVISIBILITY_ITR_ENABLED: "false"
